//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMovements
    {
        // Programýmýz çalýþtýðý anda nesneniyi ram ' çýkarmýþ ve private tanýmlayarak dýþarýdan eriþilmesini engellemiþ olduk
        private static AccountMovements instance = new AccountMovements();

        // Constructor Private olarak tanýmlayarak new anahtar sözcüðü kullanýlmasýný engeliyoruz
        private AccountMovements() { }
        // Oluþturduðunuz instace nesnemize dýþarýdan eriþilmesi için bir property tanýmladýk.
        public static AccountMovements Instance
        {
            get
            {
                return instance;
            }
        }
        public int AccountMovementCode { get; set; }
        public Nullable<System.DateTime> MovementDate { get; set; }
        public int SequenceNo { get; set; }
        public string ProcessType { get; set; }
        public string Descript { get; set; }
        public Nullable<double> Debt { get; set; }
        public Nullable<double> Credit { get; set; }
        public string Currency { get; set; }
        public Nullable<int> CurrentCode { get; set; }
    }
}
