//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        // Programýmýz çalýþtýðý anda nesneniyi ram ' çýkarmýþ ve private tanýmlayarak dýþarýdan eriþilmesini engellemiþ olduk
        private static BillDetail instance = new BillDetail();

        // Constructor Private olarak tanýmlayarak new anahtar sözcüðü kullanýlmasýný engeliyoruz
        private BillDetail() { }
        // Oluþturduðunuz instace nesnemize dýþarýdan eriþilmesi için bir property tanýmladýk.
        public static BillDetail Instance
        {
            get
            {
                return instance;
            }
        }
        public int BillDetailID { get; set; }
        public int BillCode { get; set; }
        public string LineType { get; set; }
        public Nullable<decimal> StockBarcode { get; set; }
        public Nullable<int> StockCode { get; set; }
        public string Discript { get; set; }
        public string UnitType { get; set; }
        public Nullable<decimal> IncomingAmount { get; set; }
        public Nullable<decimal> Yield { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> LineTotalAmount { get; set; }
        public Nullable<double> KdvPercent { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
    }
}
