//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentCards
    {
        // Programýmýz çalýþtýðý anda nesneniyi ram ' çýkarmýþ ve private tanýmlayarak dýþarýdan eriþilmesini engellemiþ olduk
        private static CurrentCards instance = new CurrentCards();

        // Constructor Private olarak tanýmlayarak new anahtar sözcüðü kullanýlmasýný engeliyoruz
        private CurrentCards() { }
        // Oluþturduðunuz instace nesnemize dýþarýdan eriþilmesi için bir property tanýmladýk.
        public static CurrentCards Instance
        {
            get
            {
                return instance;
            }
        }
        public string CurrentType { get; set; }
        public int CurrentCode { get; set; }
        public string CurrentName { get; set; }
        public Nullable<double> BalanceDebt { get; set; }
        public Nullable<double> BalanceCredit { get; set; }
        public string Currency { get; set; }
    }
}
