//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovements
    {
        // Programýmýz çalýþtýðý anda nesneniyi ram ' çýkarmýþ ve private tanýmlayarak dýþarýdan eriþilmesini engellemiþ olduk
        private static StockMovements instance = new StockMovements();

        // Constructor Private olarak tanýmlayarak new anahtar sözcüðü kullanýlmasýný engeliyoruz
        private StockMovements() { }
        // Oluþturduðunuz instace nesnemize dýþarýdan eriþilmesi için bir property tanýmladýk.
        public static StockMovements Instance
        {
            get
            {
                return instance;
            }
        }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ProcessType { get; set; }
        public int FreightbillNo { get; set; }
        public Nullable<int> CurrentCode { get; set; }
        public string CurrentName { get; set; }
        public Nullable<int> StockCode { get; set; }
        public Nullable<int> IncomingAmount { get; set; }
        public Nullable<int> Yield { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> BillCode { get; set; }
    }
}
